name: qr_scanner_generator
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  carousel_pro: ^0.0.13
  cupertino_icons: ^0.1.2
  http: any
  path_provider: 0.4.1
  rxdart: ^0.19.0
  flutter_swiper: ^1.1.4
  barcode_scan: ^0.0.4
  qr_flutter: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/visa_logo.png
    - assets/creditcardchipsilver.png
    - assets/card_band.jpg
    - assets/01.jpg
    - assets/02.jpg
    - assets/03.jpg
    - assets/logo_app.png
    - assets/logo_pay.png
    - assets/usuario.png
    - assets/pol-background.jpg
    - assets/card_back.jpg
    - data/initialData.json


